version: '3'

services:
  server:
    build: .
    ports:
      - "4000:4000"
    volumes:
      - ./:/opt/app
    command: make watch
  database:
    image: postgres:12.1
    ports:
      - "5432:5432"
    volumes:
      - ./.postgres:/var/lib/postgresql/data

